[project]
name = "sk-langchain-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.25",
    "langchain-openai>=0.3.19",
    "numpy>=2.2.6",
    "pydantic>=2.0.0",
]
